### ISSUE TITLE
Replace jsDelivr CDN server

### ISSUE THREAD

**Issue by eeuq7mi** [Ninterviews/Ninterviews#6]
Thanks for sharing these translations!

This website uses [jsDelivr](https://github.com/Ninterviews/Ninterviews/search?q=cdn.jsdelivr.net) as front-end CDN. However, **jsDelivr is very unstable in China mainland recently**, because it lost its ICP license in China.
(Related: 2022 May: [CSDN](https://blog.csdn.net/tsvico/article/details/124852417), [Zhihu](https://www.zhihu.com/question/533766356).  2021 December:[CSDN](https://blog.csdn.net/u010762099/article/details/122045534).) Though in July 2022, jsDelivr seems to be unblocked, **it is hard to guarantee it won't be blocked again in the near future**.

If convenient, I suggest use local js instead (storing .js files on GitHub), or use Chinese CDN Server (For example, [CSDN blog](https://blog.csdn.net/tsvico/article/details/124852417)).

By the way, [the main site](https://github.com/Xzonn/xzonn.github.io/search?q=cdn.jsdelivr.net) also suffers from the same problem.

---
Replace:
`https://cdn.jsdelivr.net/npm/algoliasearch@4.9.1/dist/algoliasearch-lite.umd.js`
With:
`https://code.bdstatic.com/npm/algoliasearch@4.9.1/dist/algoliasearch-lite.umd.js`

```
Use Baidu CDN:
https://code.bdstatic.com/npm/instantsearch.js@4.23.0/dist/instantsearch.production.min.js
https://code.bdstatic.com/npm/jquery@3.6.0/dist/jquery.min.js
https://code.bdstatic.com/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js

Use ele.me CDN:
https://npm.elemecdn.com/bootstrap@3.4.1/dist/fonts/
```
---
**Update:**
Zhihu CDN server is not very reliable (see [this](https://www.zhihu.com/question/513332990)), so zhihu CDN server is not preferred.

**Comment by Xzonn** [comment]
Thanks for the information, I've replaced jsDelivr CDN with Baidu CDN. I hope it works well.

**Comment by eeuq7mi** [comment]
Thanks.
